name: ydemetriades/bitbucket-server-v1-buildstatus
image: ydemetriades/bitbucket-server-v1-buildstatus
tag: 0.0.1
version: 0.0.1
description: Update BitBucket Commit Build Status
categories:
- git
keywords:
- git
- bitbucket
- bitbucketserver
- buildstatus
sources:
- https://github.com/ydemetriades/codefresh-bitbucket-server-v1-buildstatus
maintainers:
- name: Yiannis Demetriades
  email: yiannis.demetriades@gmail.com
icon: https://raw.githubusercontent.com/ydemetriades/codefresh-bitbucket-server-v1-buildstatus/master/icon.jpg
envs:
- name: BB_BSN_URL
  type: required
  description: Bitbucket API Url.
- name: BB_BSN_REPO_AUTH_USER
  type: required
  description: Bitbucket API Authorization Username
- name: BB_BSN_REPO_AUTH_PASSWORD
  type: required
  description: Bitbucket API Authorization Password
- name: CF_BUILD_STATUS
  type: required
  description: Build Status. Must be one of ['SUCCESSFUL', 'FAILED', 'INPROGRESS', 'STOPPED']